### ISSUE TITLE
postgis20 fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-versions#904]
```
==> Installing homebrew/versions/postgis20
==> Downloading http://download.osgeo.org/postgis/source/postgis-2.0.7.tar.gz
######################################################################## 100,0%
==> Patching
patching file configure.ac
==> ./autogen.sh
==> ./configure --with-projdir=/usr/local --with-jsondir=/usr/local/opt/json-c --with-pgconfig=/usr/
==> make
      _geom_from_geojson in lwgeom_in_geojson.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [postgis-2.0.so] Error 1
make: *** [all] Error 1
```

Logs: https://gist.github.com/adc08cd29e2dd2350915

**Comment by DomT4** [comment]
Unless upstream have a new release for this I'm tempted to kill it; It breaks regularly after either `json-c` or `gdal` are updated.

**Comment by DomT4** [comment]
Formula was killed.
