### ISSUE TITLE
cassandra22 - cqlsh error AttributeError: 'list' object has no attribute 'has_more_pages'

### ISSUE THREAD

**Issue by ckhall** [Homebrew/homebrew-versions#1131]
after a fresh install of cassandra22, any select query, whether from an existing system table or a user defined table, results in the the above error, debug output below:

```bash
➜  ~  brew install cassandra22
==> Installing cassandra22 from homebrew/versions
==> Downloading https://www.apache.org/dyn/closer.cgi?path=/cassandra/2.2.4/apache-cassandra-2.2.4-bin.tar.gz
==> Best Mirror http://mirrors.sonic.net/apache/cassandra/2.2.4/apache-cassandra-2.2.4-bin.tar.gz
######################################################################## 100.0%
==> Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-12.0.5.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/cassandra22/2.2.4/libexec/vendor --single-version-externally-managed --reco
==> Downloading https://pypi.python.org/packages/source/t/thrift/thrift-0.9.2.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/cassandra22/2.2.4/libexec/vendor --single-version-externally-managed --reco
==> Downloading https://pypi.python.org/packages/source/f/futures/futures-2.2.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/cassandra22/2.2.4/libexec/vendor --single-version-externally-managed --reco
==> Downloading https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/cassandra22/2.2.4/libexec/vendor --single-version-externally-managed --reco
==> Downloading https://pypi.python.org/packages/source/c/cql/cql-1.4.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/cassandra22/2.2.4/libexec/vendor --single-version-externally-managed --reco
==> Downloading https://pypi.python.org/packages/source/c/cassandra-driver/cassandra-driver-2.6.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/cassandra22/2.2.4/libexec/vendor --single-version-externally-managed --reco
==> Caveats
To load homebrew/versions/cassandra22:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.cassandra22.plist
==> Summary
🍺  /usr/local/Cellar/cassandra22/2.2.4: 4,707 files, 103.6M, built in 16 seconds
➜  ~  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.cassandra22.plist
➜  ~  cqlsh --debug
Using CQL driver: <module 'cassandra' from '/usr/local/Cellar/cassandra22/2.2.4/libexec/vendor/lib/python2.7/site-packages/cassandra/__init__.pyc'>
Using connect timeout: 5 seconds
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.2.4 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> desc keyspaces;

system_traces  system_auth  system  system_distributed

cqlsh> use system_auth;
cqlsh:system_auth> desc tables;

resource_role_permissons_index  role_permissions  role_members  roles

cqlsh:system_auth> select * from roles;

Traceback (most recent call last):
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1110, in onecmd
    self.handle_statement(st, statementtext)
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1147, in handle_statement
    return custom_handler(parsed)
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1179, in do_select
    self.perform_statement(statement)
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1184, in perform_statement
    success, future = self.perform_simple_statement(stmt)
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1235, in perform_simple_statement
    self.print_result(result, self.parse_for_table_meta(statement.query_string))
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1251, in print_result
    if result.has_more_pages and self.tty:
AttributeError: 'list' object has no attribute 'has_more_pages'
cqlsh> create keyspace test with replication = { 'class': 'SimpleStrategy', 'replication_factor': 1 };
cqlsh> use test;
cqlsh:test> create table foobar ( a uuid PRIMARY KEY, b text);
cqlsh:test> desc foobar;

CREATE TABLE test.foobar (
    a uuid PRIMARY KEY,
    b text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh:test> select * from foobar;

Traceback (most recent call last):
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1110, in onecmd
    self.handle_statement(st, statementtext)
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1147, in handle_statement
    return custom_handler(parsed)
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1179, in do_select
    self.perform_statement(statement)
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1184, in perform_statement
    success, future = self.perform_simple_statement(stmt)
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1235, in perform_simple_statement
    self.print_result(result, self.parse_for_table_meta(statement.query_string))
  File "/usr/local/Cellar/cassandra22/2.2.4/libexec/bin/cqlsh.py", line 1251, in print_result
    if result.has_more_pages and self.tty:
AttributeError: 'list' object has no attribute 'has_more_pages'
cqlsh:system_auth> exit
```

**Comment by mikemcquaid** [comment]
@ckhall Can you see if you can reproduce this on a non-Homebrew Cassandra?

**Comment by ckhall** [comment]
@mikemcquaid working on a binary install of 2.2.4 as we speak...i'll drop the details when I finish.

**Comment by ckhall** [comment]
@mikemcquaid works fine with binary install of cassandra 2.2.4.

```bash
➜  ~  mkdir ~/opt/packages && cd ~/opt/packages
➜  ~  cd ~/opt/packages
➜  ~/opt/packages  curl -O http://apache.arvixe.com/cassandra/2.2.4/apache-cassandra-2.2.4-bin.tar.gz
➜  ~/opt/packages  tar -xvzf apache-cassandra-2.2.4-bin.tar.gz
➜  ~/opt/packages  ln -s ~/opt/packages/apache-cassandra-2.2.4 ~/opt/cassandra
➜  ~/opt/packages  mkdir -p ~/opt/cassandra/data/data && mkdir -p ~/opt/cassandra/data/commitlog && mkdir -p ~/opt/cassandra/data/saved_caches && mkdir -p ~/opt/cassandra/logs
➜  ~/opt/packages  cd
➜  ~  ~/opt/cassandra/bin/cassandra -f

(another terminal)
➜  ~  ~/opt/cassandra/bin/cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.2.4 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> desc keyspaces;

system_traces  system_auth  system  system_distributed

cqlsh> use system_auth
   ... ;
cqlsh:system_auth> desc tables;

resource_role_permissons_index  role_permissions  role_members  roles

cqlsh:system_auth> select * from roles;

 role      | can_login | is_superuser | member_of | salted_hash
-----------+-----------+--------------+-----------+--------------------------------------------------------------
 cassandra |      True |         True |      null | $2a$10$CtlTydOgUUpnqMvcH6Bqgu/GgEUCz25KtA7rhAuhXUTNttdPmX6NC

(1 rows)
cqlsh:system_auth>
```

**Comment by ckhall** [comment]
@mikemcquaid ok, so tracked this down to the 2.6.0 cassandra-driver.  it looks like the 2.2.4 binary comes with 3.0.0 driver.  I edited the formula to use 3.0.0, reinstalled cassandra22 and it works correctly now.

**Comment by eprothro** [comment]
@ckhall thanks for the efforts, been banging my head against the wall for a few hours on this. Since others might have the same question: how do we get this updated formula?

I've run `brew update`, but `brew edit` still reflects the previous formula, and I have to manually apply this patch to get it working. Am I missing something obvious as to how to get the fixed formula?
